"""empty message

Revision ID: 9fec006ffc05
Revises: f30c913e3578
Create Date: 2020-07-02 14:54:24.416730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fec006ffc05'
down_revision = 'f30c913e3578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_role',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('organization_id', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('org_roles_users',
    sa.Column('user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('role_id', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.add_column('tournament', sa.Column('organization_id', sa.CHAR(length=36), nullable=True))
    op.create_foreign_key(None, 'tournament', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.drop_column('tournament', 'organization_id')
    op.drop_table('org_roles_users')
    op.drop_table('org_role')
    op.drop_table('organization')
    # ### end Alembic commands ###
